const resList = [
  {
    info: {
      id: "234903",
      name: "Meghana Foods",
      cloudinaryImageId: "e0vvulfbahjxjz6k4uwi",
      locality: "Residency Road",
      areaName: "Shanti Nagar",
      costForTwo: "₹500 for two",
      cuisines: ["Biryani", "Andhra", "South Indian", "North Indian"],
      avgRating: 4.5,
      parentId: "635",
      avgRatingString: "4.5",
      totalRatingsString: "10K+",
      sla: {
        deliveryTime: 23,
        lastMileTravel: 1.4,
        serviceability: "SERVICEABLE",
        slaString: "23 mins",
      },
    },
  },
  {
    info: {
      id: "425",
      name: "Hotel Empire",
      cloudinaryImageId: "un4omn7rcunkmlw6vikr",
      locality: "Domlur",
      areaName: "Indiranagar",
      costForTwo: "₹450 for two",
      cuisines: ["North Indian", "Kebabs", "Biryani"],
      avgRating: 4.1,
      parentId: "475",
      avgRatingString: "4.1",
      totalRatingsString: "10K+",
      sla: {
        deliveryTime: 30,
        lastMileTravel: 4.6,
        serviceability: "SERVICEABLE",
        slaString: "30 mins",
      },
    },
  },
  {
    info: {
      id: "23847",
      name: "Domino's Pizza",
      cloudinaryImageId: "bz9zkh2aqywjhpankb07",
      locality: "Rest House Road",
      areaName: "Brigade Road",
      costForTwo: "₹400 for two",
      cuisines: ["Pizzas", "Italian", "Pastas", "Desserts"],
      avgRating: 4.3,
      parentId: "2456",
      avgRatingString: "4.3",
      totalRatingsString: "5K+",
      sla: {
        deliveryTime: 25,
        serviceability: "SERVICEABLE",
        slaString: "25 mins",
      },
    },
  },
  {
    info: {
      id: "229",
      name: "Meghana Biryani",
      cloudinaryImageId: "wgcc304pp1zgalaoboi8",
      locality: "Koramangala",
      areaName: "Koramangala",
      costForTwo: "₹500 for two",
      cuisines: ["Biryani", "Andhra", "South Indian"],
      avgRating: 4.6,
      parentId: "635",
      avgRatingString: "4.6",
      totalRatingsString: "15K+",
      sla: {
        deliveryTime: 28,
        lastMileTravel: 2.5,
        serviceability: "SERVICEABLE",
        slaString: "28 mins",
      },
    },
  },
  {
    info: {
      id: "393840",
      name: "Chinese Wok",
      cloudinaryImageId: "e0839ff574213e6f35b3899ebf1fc597",
      locality: "Chikka Lakshmaiah Layout",
      areaName: "Adugodi",
      costForTwo: "₹250 for two",
      cuisines: ["Chinese", "Asian", "Tibetan", "Desserts"],
      avgRating: 3.8,
      parentId: "61955",
      avgRatingString: "3.8",
      totalRatingsString: "1K+",
      sla: {
        deliveryTime: 35,
        lastMileTravel: 2.0,
        serviceability: "SERVICEABLE",
        slaString: "35 mins",
      },
    },
  },
  {
    info: {
      id: "337335",
      name: "Kannur Food Court",
      cloudinaryImageId: "bmwn4n4bn6n1tcpc8x2h",
      locality: "BTM Layout",
      areaName: "Koramangala",
      costForTwo: "₹300 for two",
      cuisines: ["Kerala", "Biryani", "Beverages"],
      avgRating: 3.9,
      parentId: "114756",
      avgRatingString: "3.9",
      totalRatingsString: "8K+",
      sla: {
        deliveryTime: 32,
        lastMileTravel: 3.0,
        serviceability: "SERVICEABLE",
        slaString: "32 mins",
      },
    },
  },
  {
    info: {
      id: "56589",
      name: "KFC",
      cloudinaryImageId:
        "RX_THUMBNAIL/IMAGES/VENDOR/2024/4/17/510f05e2-a9e7-49fe-8ab3-ea8c2eb8a5ae_56589.JPG",
      locality: "Brigade Road",
      areaName: "Central Bangalore",
      costForTwo: "₹400 for two",
      cuisines: ["Burgers", "Fast Food", "Rolls & Wraps"],
      avgRating: 4.2,
      parentId: "547",
      avgRatingString: "4.2",
      totalRatingsString: "12K+",
      sla: {
        deliveryTime: 22,
        lastMileTravel: 1.8,
        serviceability: "SERVICEABLE",
        slaString: "22 mins",
      },
    },
  },
  {
    info: {
      id: "43836",
      name: "McDonald's",
      cloudinaryImageId:
        "RX_THUMBNAIL/IMAGES/VENDOR/2024/4/1/fedaee6f-c5e9-4f19-8188-93627e6d6776_43836.JPG",
      locality: "MG Road",
      areaName: "Ashok Nagar",
      costForTwo: "₹400 for two",
      cuisines: ["Burgers", "Beverages", "Cafe", "Desserts"],
      avgRating: 4.4,
      parentId: "630",
      avgRatingString: "4.4",
      totalRatingsString: "20K+",
      sla: {
        deliveryTime: 26,
        lastMileTravel: 2.2,
        serviceability: "SERVICEABLE",
        slaString: "26 mins",
      },
    },
  },
];

export default resList;
